#!/bin/bash
# Commands to review Lambda function for URL handling issues

# Set your Lambda function details
FUNCTION_NAME="Master_Function"
REGION="us-east-1"  # Change to your region

echo "Lambda Function Review Commands"
echo "=============================="
echo ""
echo "1. Download Lambda function code:"
echo "aws lambda get-function --function-name $FUNCTION_NAME --region $REGION --query 'Code.Location' --output text | xargs curl -o lambda-code.zip"
echo ""
echo "2. Extract the code:"
echo "unzip lambda-code.zip -d lambda-review/"
echo ""
echo "3. Search for URL/markdown processing:"
echo "cd lambda-review/"
echo ""
echo "# Find text manipulation that might strip URLs:"
echo "grep -n -E '\.strip\(|\.replace\(|re\.sub\(' *.py"
echo ""
echo "# Find response formatting:"
echo "grep -n -E 'return.*content|response.*=|format.*response' response_formatter.py"
echo ""
echo "# Find Bedrock response handling:"
echo "grep -n -A5 -B5 'bedrock.*response' bedrock_handler.py"
echo ""
echo "# Find content extraction:"
echo "grep -n -E 'get.*content|extract.*message' *.py"
echo ""
echo "4. Check specific files:"
echo "cat response_formatter.py | less"
echo "cat bedrock_handler.py | less"
echo ""
echo "5. Look for these specific issues:"
echo "- Any .strip() operations on content"
echo "- Converting markdown to plain text"
echo "- Multiple JSON encoding layers"
echo "- Regex operations that might match URLs"