AWSTemplateFormatVersion: '2010-09-09'
Description: 'PICASSO Unified Coordination Architecture - DynamoDB Tables Only'

Parameters:
  Environment:
    Type: String
    AllowedValues: [staging, production]
    Default: staging
    Description: Deployment environment

Conditions:
  IsProduction: !Equals [!Ref Environment, production]

Resources:
  # DynamoDB Tables for Unified Architecture
  ConversationSummariesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${Environment}-conversation-summaries'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: sessionId
          AttributeType: S
        - AttributeName: tenantId
          AttributeType: S
      KeySchema:
        - AttributeName: sessionId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: tenantId-index
          KeySchema:
            - AttributeName: tenantId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: expires_at
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !If [IsProduction, true, false]
      DeletionProtectionEnabled: !If [IsProduction, true, false]
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: conversation-summaries
        - Key: TTL
          Value: 7-days

  RecentMessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${Environment}-recent-messages'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: sessionId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: sessionId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: expires_at
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !If [IsProduction, true, false]
      DeletionProtectionEnabled: !If [IsProduction, true, false]
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: recent-messages
        - Key: TTL
          Value: 24-hours

Outputs:
  ConversationSummariesTableName:
    Description: 'Conversation Summaries DynamoDB Table'
    Value: !Ref ConversationSummariesTable
    Export:
      Name: !Sub '${Environment}-SummariesTable'

  RecentMessagesTableName:
    Description: 'Recent Messages DynamoDB Table'
    Value: !Ref RecentMessagesTable
    Export:
      Name: !Sub '${Environment}-MessagesTable'

  ConversationSummariesTableArn:
    Description: 'Conversation Summaries DynamoDB Table ARN'
    Value: !GetAtt ConversationSummariesTable.Arn
    Export:
      Name: !Sub '${Environment}-SummariesTableArn'

  RecentMessagesTableArn:
    Description: 'Recent Messages DynamoDB Table ARN'
    Value: !GetAtt RecentMessagesTable.Arn
    Export:
      Name: !Sub '${Environment}-MessagesTableArn'