AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'PICASSO Unified Coordination Architecture - Function URLs with JWT Authentication'

Parameters:
  Environment:
    Type: String
    AllowedValues: [staging, production]
    Default: staging
    Description: Deployment environment
  
  CloudFrontDomain:
    Type: String
    Description: CloudFront domain for widget distribution
    Default: chat.myrecruiter.ai
  
  S3Bucket:
    Type: String
    Description: S3 bucket for tenant configurations
    Default: myrecruiter-picasso
  
  JwtSecretKeyName:
    Type: String
    Description: AWS Secrets Manager key name for JWT signing
    Default: picasso/jwt/signing-key

Conditions:
  IsProduction: !Equals [!Ref Environment, production]
  IsStaging: !Equals [!Ref Environment, staging]

Globals:
  Function:
    Runtime: python3.9
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        CLOUDFRONT_DOMAIN: !Ref CloudFrontDomain
        S3_BUCKET: !Ref S3Bucket
        JWT_SECRET_KEY_NAME: !Ref JwtSecretKeyName

Resources:
  # DynamoDB Tables for Unified Architecture
  ConversationSummariesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${Environment}-conversation-summaries'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: tenantId
          AttributeType: S
        - AttributeName: sessionId
          AttributeType: S
      KeySchema:
        - AttributeName: tenantId
          KeyType: HASH
        - AttributeName: sessionId
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: sessionId-index
          KeySchema:
            - AttributeName: sessionId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !If [IsProduction, true, false]
      DeletionProtectionEnabled: !If [IsProduction, true, false]
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: conversation-summaries
        - Key: TTL
          Value: 7-days

  RecentMessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${Environment}-recent-messages'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: sessionId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: sessionId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !If [IsProduction, true, false]
      DeletionProtectionEnabled: !If [IsProduction, true, false]
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: recent-messages
        - Key: TTL
          Value: 24-hours

  # JWT Secret in Secrets Manager
  JwtSigningSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref JwtSecretKeyName
      Description: JWT signing key for Function URL authentication
      GenerateSecretString:
        SecretStringTemplate: '{}'
        GenerateStringKey: signingKey
        PasswordLength: 64
        ExcludeCharacters: '"@/\'
      ReplicationRegions:
        - !If 
          - IsProduction
          - Region: us-west-2
          - !Ref AWS::NoValue
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: jwt-signing

  # Master Function (existing, but with enhanced permissions)
  MasterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Environment}-Master-Function'
      CodeUri: ../lambda-review/
      Handler: lambda_function.lambda_handler
      Environment:
        Variables:
          SUMMARIES_TABLE_NAME: !Ref ConversationSummariesTable
          MESSAGES_TABLE_NAME: !Ref RecentMessagesTable
          BEDROCK_STREAMING_FUNCTION_NAME: !Ref BedrockStreamingHandler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ConversationSummariesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref RecentMessagesTable
        - S3ReadPolicy:
            BucketName: !Ref S3Bucket
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref JwtSigningSecret
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: !GetAtt BedrockStreamingHandler.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref ApiGateway
      Tags:
        Environment: !Ref Environment
        Purpose: master-coordination

  # NEW: Bedrock Streaming Handler with Function URL
  BedrockStreamingHandler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Environment}-Bedrock-Streaming-Handler'
      CodeUri: ../streaming/
      Handler: streaming_handler.lambda_handler
      Timeout: 900  # 15 minutes for long streaming responses
      MemorySize: 1024
      Environment:
        Variables:
          SUMMARIES_TABLE_NAME: !Ref ConversationSummariesTable
          MESSAGES_TABLE_NAME: !Ref RecentMessagesTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ConversationSummariesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref RecentMessagesTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
                - bedrock-agent-runtime:Retrieve
              Resource: '*'
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref JwtSigningSecret
      Tags:
        Environment: !Ref Environment
        Purpose: streaming-handler

  # Function URL for Bedrock Streaming Handler (AuthType: NONE)
  BedrockStreamingFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      TargetFunctionArn: !GetAtt BedrockStreamingHandler.Arn
      AuthType: NONE  # Critical: NONE for browser compatibility
      Cors:
        AllowCredentials: false
        AllowHeaders:
          - Content-Type
          - Authorization
          - x-api-key
          - x-jwt-token
        AllowMethods:
          - GET
          - POST
          - OPTIONS
        AllowOrigins:
          - "*"
        ExposeHeaders:
          - x-stream-id
          - x-session-id
        MaxAge: 86400

  # Permission for Function URL invocation
  BedrockStreamingFunctionUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt BedrockStreamingHandler.Arn
      Action: lambda:InvokeFunctionUrl
      Principal: '*'
      FunctionUrlAuthType: NONE

  # API Gateway (existing, but now only for Master Function)
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub '${Environment}-picasso-api'
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      BinaryMediaTypes:
        - '*/*'
      Tags:
        Environment: !Ref Environment
        Purpose: master-function-gateway

  # CloudWatch Log Groups with appropriate retention
  MasterFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${Environment}-Master-Function'
      RetentionInDays: !If [IsProduction, 30, 7]
      Tags:
        - Key: Environment
          Value: !Ref Environment

  BedrockStreamingLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${Environment}-Bedrock-Streaming-Handler'
      RetentionInDays: !If [IsProduction, 30, 7]
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # CloudWatch Alarms for monitoring
  MasterFunctionErrorRate:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${Environment}-Master-Function-ErrorRate'
      AlarmDescription: 'Master Function error rate too high'
      MetricName: ErrorRate
      Namespace: AWS/Lambda
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 0.05  # 5% error rate
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref MasterFunction
      TreatMissingData: notBreaching

  BedrockStreamingLatency:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${Environment}-Streaming-Function-Latency'
      AlarmDescription: 'Streaming Function first token latency too high'
      MetricName: Duration
      Namespace: AWS/Lambda
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 5000  # 5 seconds (should be <1s for first token)
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref BedrockStreamingHandler
      TreatMissingData: notBreaching

Outputs:
  MasterFunctionUrl:
    Description: 'Master Function API Gateway URL'
    Value: !Sub 'https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/'
    Export:
      Name: !Sub '${Environment}-MasterFunctionUrl'

  BedrockStreamingFunctionUrl:
    Description: 'Bedrock Streaming Function URL (AuthType: NONE)'
    Value: !GetAtt BedrockStreamingFunctionUrl.FunctionUrl
    Export:
      Name: !Sub '${Environment}-StreamingFunctionUrl'

  ConversationSummariesTableName:
    Description: 'Conversation Summaries DynamoDB Table'
    Value: !Ref ConversationSummariesTable
    Export:
      Name: !Sub '${Environment}-SummariesTable'

  RecentMessagesTableName:
    Description: 'Recent Messages DynamoDB Table'
    Value: !Ref RecentMessagesTable
    Export:
      Name: !Sub '${Environment}-MessagesTable'

  JwtSecretArn:
    Description: 'JWT Signing Secret ARN'
    Value: !Ref JwtSigningSecret
    Export:
      Name: !Sub '${Environment}-JwtSecret'